### ISSUE TITLE
Provide option to create layer for specific gem groups

### ISSUE THREAD

**Issue by faizaankhan** [navarasu/serverless-ruby-layer#28]
I am using RSpec testing, and I couldn't ignore having Rspec in my Lambda Layer. If there is an option to bundle ignoring gem groups like `bundle install --without= test`, it would be nice to have.

**Comment by navarasu** [comment]
By default, it excludes the `test` and `development` group in bundle install. Gems mentioned in development and test

**Comment by faizaankhan** [comment]
Thank you. That solves my problem.

**Comment by navarasu** [comment]
Added documentation and test cases for exclude test/development gems option
