### ISSUE TITLE
Release 1.6.0 Milestone

### ISSUE THREAD

**Issue by jagthedrummer** [navarasu/serverless-ruby-layer#61]
Any chance for a 1.5.1 release to pick up some of the newest updates?

**Comment by navarasu** [comment]
@jagthedrummer Sorry for the long delay. I will work on this week

**Comment by 4xposed** [comment]
@navarasu any ETA?

**Comment by DavidSelby** [comment]
@navarasu Also hoping for a release here. Is it still being maintained? Would be great to be able to pass env variables to docker.

**Comment by navarasu** [comment]
I will release this by May 1

**Comment by DavidSelby** [comment]
@navarasu Any luck?

**Comment by navarasu** [comment]
Code clean-up is done and issues are fixed in the exiting environment codes. Added proper test cases to test environment feature.
Currently updating all example ruby 2.5 to 2.7. Updating the docs as per the new changes.

**Comment by navarasu** [comment]
- [ ] Currently updating the docs as per the new changes.

**Comment by navarasu** [comment]
Finally, it is done. 👍🏼  Thanks for your patience :pray:
### Released 1.6.0 version 🎉
This brings the environment option to pass environment variable to the docker bundler / docker file.
Please check the examples and docs. [Docker Example](https://github.com/navarasu/serverless-ruby-layer/blob/master/examples/use-docker-with-environment) - [DockerFile Example](https://github.com/navarasu/serverless-ruby-layer/blob/master/examples/use-docker-file-with-environment) - [Docs](https://navarasu.github.io/serverless-ruby-layer/#/environment)

**Comment by navarasu** [comment]
@DavidSelby @jagthedrummer @4xposed 

Finally, it is done. 👍🏼  Thanks for your patience :pray:
### Released 1.6.0 version 🎉
This brings the environment option to pass environment variable to the docker bundler / docker file.
Please check the examples and docs. [Docker Example](https://github.com/navarasu/serverless-ruby-layer/blob/master/examples/use-docker-with-environment) - [DockerFile Example](https://github.com/navarasu/serverless-ruby-layer/blob/master/examples/use-docker-file-with-environment) - [Docs](https://navarasu.github.io/serverless-ruby-layer/#/environment)
