### ISSUE TITLE
Support for Ruby 3.2 Runtime

### ISSUE THREAD

**Issue by ghosteathuman** [navarasu/serverless-ruby-layer#85]
**Is your feature request related to a problem? Please describe.**
AWS Lamba has [added support](https://aws.amazon.com/about-aws/whats-new/2023/06/aws-lambda-support-ruby-3-2/) for the Ruby 3.2 runtime.

The serverless-ruby-layer `use_docker` option, when set to `true`, uses the [lambci/lambda](https://github.com/lambci/docker-lambda) docker images, which project seems to be have been archived and wouldn't have a Docker image for Ruby 3.2.

**Describe the solution you'd like**
Support for Ruby 3.2 runtime is available. The `use_docker` option, when set to `true`, will use an appropriate Docker image for Ruby 3.2.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by starverdiyev** [comment]
AWS will deprecate ruby 2.7 layer in december 2023. So this updates to layer 3.2 is very important

**Comment by nodanaonlyzuul** [comment]
First - thanks to @navarasu and other contributors to this repository.

@navarasu  - has there been any investigation into switching this repo to use the [aws/aws-lambda-base-images images](https://github.com/aws/aws-lambda-base-images/tree/ruby3.2) per [lambci/lambda](https://github.com/lambci/docker-lambda)'s deprecation suggestion?

@ghosteathuman  / @starverdiyev  - in the meantime - my team is using [this repo's use_docker_file example](https://github.com/navarasu/serverless-ruby-layer/tree/master/examples/use-docker-file) and a minimal Dockerfile based on either `aws-lambda-ruby:3.2` (base image) or the official `ruby:3.2` image.

**Comment by navarasu** [comment]
Thank you all. Happy to see the issues. Not sure how I missed this issue raised 3 months back. I will work on this asap. 😊

**Comment by nodanaonlyzuul** [comment]
Thanks @navarasu !

joshuaflanagan/serverless-ruby-package also added 3.2 support and moved to using [aws/aws-lambda-base-images images](https://github.com/aws/aws-lambda-base-images/tree/ruby3.2) in [this PR](https://github.com/joshuaflanagan/serverless-ruby-package/pull/51) if it can serve as inspiration.

**Comment by navarasu** [comment]
@nodanaonlyzuul We already have a PR for this change. I merged it. I will update the old examples and will spin a new release. Thank you for your support

**Comment by starverdiyev** [comment]
@navarasu when new release will be available? I see that the last release is 1.6.0.

Thank you!

**Comment by nodanaonlyzuul** [comment]
Hello! 

I'm also curious when a new version will be available. Thanks for the fast turnaround on the PR!

**Comment by navarasu** [comment]
@nodanaonlyzuul @starverdiyev Released 1.7.0 version with 3.2 support. Also updated examples

**Comment by nodanaonlyzuul** [comment]
Thank you SO much @navarasu !
